name: Deploy Frontend to S3

on:
  push:
    branches:
      - main # Dispara o deploy automaticamente sempre que houver um push na branch main

jobs:
  deploy-s3:
    runs-on: ubuntu-latest

    steps:
      # 1. Puxa o código mais recente do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura as credenciais da AWS de forma segura usando as Secrets
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ajuste para a região do seu bucket (ex: sa-east-1)

      # 3. Sincroniza os arquivos do site diretamente com o Bucket S3
      - name: Enviar arquivos para o S3
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"